apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-smr
  labels:
    app: req-smr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: req-smr
  template:
    metadata:
      labels:
        app: req-smr
    spec:
      containers:
        - name: req-smr
          image: lucasbfernandes/req-smr:v04
          ports:
            - containerPort: 8080