apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-smr
  labels:
    app: req-smr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: req-smr
  template:
    metadata:
      labels:
        app: req-smr
    spec:
      initContainers:
        - name: init-networking
          image: lucasbfernandes/proxy-setup:v10
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
        - name: nodejs-app
          image: lucasbfernandes/nodejs-app:v10
          ports:
            - containerPort: 80
        - name: req-smr
          image: lucasbfernandes/req-smr:v10
          ports:
            - containerPort: 8080
